using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BooksMVC.Models
{
    public class BookModel
    {
        // BookID is the primary key and will be auto-generated by the database.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int BookID { get; set; }

        // BookName is required and has a maximum length.
        [Required(ErrorMessage = "Book Name is required.")]
        [StringLength(100, ErrorMessage = "Book Name cannot exceed 100 characters.")]
        [Display(Name = "Book Name")] // Display name for UI
        public string BookName { get; set; }

        // BookAuthor is required and has a maximum length.
        [Required(ErrorMessage = "Author Name is required.")]
        [StringLength(100, ErrorMessage = "Author Name cannot exceed 100 characters.")]
        [Display(Name = "Author Name")]
        public string BookAuthor { get; set; }

        // BookPrice is required and must be a positive number.
        [Required(ErrorMessage = "Price is required.")]
        [Range(0.01, 10000.00, ErrorMessage = "Price must be between 0.01 and 10000.00.")]
        [DataType(DataType.Currency)] // Suggests currency formatting in UI
        [Display(Name = "Price")]
        public decimal BookPrice { get; set; }
    }
}
